import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "../lib/apollo/wrapper";
import Providers from "@/components/ui/providers";
import CustomToaster from "../components/custom-toaster";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <Providers>
          <ApolloWrapper>
            {children}
            <CustomToaster />
          </ApolloWrapper>
        </Providers>
      </body>
    </html>
  );
}
